// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: income.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
WITH inserted AS (
    INSERT INTO incomes(id, name, amount, category, date, note, user_id)
    VALUES ($1, $2, $3, $4,$5, $6, $7)
    RETURNING id, name, amount, category, date, note, user_id, created_at, updated_at
)
SELECT inserted.id,
    inserted."name",
    inserted.amount,
    categories."name" AS category,
    inserted."date",
    inserted.note,
    users."name" AS user,
    inserted.created_at,
    inserted.updated_at
FROM inserted
INNER JOIN users ON inserted.user_id = users.id
INNER JOIN categories ON inserted.category = categories.id
`

type CreateIncomeParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Amount   pgtype.Numeric `json:"amount"`
	Category uuid.UUID      `json:"category"`
	Date     pgtype.Date    `json:"date"`
	Note     *string        `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

type CreateIncomeRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (CreateIncomeRow, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Date,
		arg.Note,
		arg.UserID,
	)
	var i CreateIncomeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Date,
		&i.Note,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :execresult
DELETE FROM incomes where id = $1 AND user_id=$2
`

type DeleteIncomeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteIncome(ctx context.Context, arg DeleteIncomeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteIncome, arg.ID, arg.UserID)
}

const getIncome = `-- name: GetIncome :many
SELECT incomes.id,
    incomes."name",
    incomes.amount,
    categories."name" AS category,
    incomes."date",
    incomes.note,
    users."name" AS user,
    incomes.created_at,
    incomes.updated_at
FROM incomes
INNER JOIN users ON incomes.user_id = users.id
INNER JOIN categories ON incomes.category  = categories.id
WHERE incomes.user_id=$1
ORDER BY incomes.date DESC
`

type GetIncomeRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetIncome(ctx context.Context, userID uuid.UUID) ([]GetIncomeRow, error) {
	rows, err := q.db.Query(ctx, getIncome, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncomeRow
	for rows.Next() {
		var i GetIncomeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Category,
			&i.Date,
			&i.Note,
			&i.User,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncome = `-- name: UpdateIncome :one
WITH updated AS (
    UPDATE incomes
    SET name = $2,
        amount = $3,
        category =  $4,
        date = $5,
        note = $6
    WHERE incomes.id = $1 AND incomes.user_id=$7
    RETURNING id, name, amount, category, date, note, user_id, created_at, updated_at
)
SELECT updated.id,
    updated."name",
    updated.amount,
    categories."name" AS category,
    updated."date",
    updated.note,
    users."name" AS user,
    updated.created_at,
    updated.updated_at
FROM updated
INNER JOIN users ON updated.user_id = users.id
INNER JOIN categories ON updated."category" = categories.id
`

type UpdateIncomeParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Amount   pgtype.Numeric `json:"amount"`
	Category uuid.UUID      `json:"category"`
	Date     pgtype.Date    `json:"date"`
	Note     *string        `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

type UpdateIncomeRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (UpdateIncomeRow, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Date,
		arg.Note,
		arg.UserID,
	)
	var i UpdateIncomeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Date,
		&i.Note,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
