// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: investment.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestment = `-- name: CreateInvestment :one
WITH inserted AS (
    INSERT INTO investments(id, name, amount, category, date, note, user_id)
    VALUES ($1, $2, $3, $4,$5, $6, $7)
    RETURNING id, name, amount, category, date, note, user_id, created_at, updated_at
)
SELECT inserted.id,
    inserted."name",
    inserted.amount,
    categories."name" AS category,
    inserted."date",
    inserted.note,
    users."name" AS user,
    inserted.created_at,
    inserted.updated_at
FROM inserted
INNER JOIN users ON inserted.user_id = users.id
INNER JOIN categories ON inserted.category = categories.id
`

type CreateInvestmentParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Amount   pgtype.Numeric `json:"amount"`
	Category uuid.UUID      `json:"category"`
	Date     pgtype.Date    `json:"date"`
	Note     *string        `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

type CreateInvestmentRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (CreateInvestmentRow, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Date,
		arg.Note,
		arg.UserID,
	)
	var i CreateInvestmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Date,
		&i.Note,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
