// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID     uuid.UUID
	Name   string
	Amount int32
	Type   string
	Date   pgtype.Date
	Note   *string
	UserID uuid.UUID
}

type TransactionType struct {
	ID          uuid.UUID
	Name        string
	Description *string
}

type User struct {
	ID             uuid.UUID
	Name           string
	Username       string
	HashedPassword string
}
