// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
WITH inserted AS (
    INSERT INTO transaction(id, name, amount, category, date, note, user_id)
    VALUES ($1, $2, $3, $4,$5, $6, $7)
    RETURNING id, name, amount, category, date, note, user_id, created_at, updated_at
)
SELECT inserted.id,
    inserted."name",
    inserted.amount,
    category."name" AS category,
    inserted."date",
    inserted.note,
    account."name" AS user,
    inserted.created_at,
    inserted.updated_at
FROM inserted
INNER JOIN account ON inserted.user_id = account.id
INNER JOIN category ON inserted."category" = category.id
`

type CreateTransactionParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Amount   pgtype.Numeric `json:"amount"`
	Category uuid.UUID      `json:"category"`
	Date     pgtype.Date    `json:"date"`
	Note     *string        `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

type CreateTransactionRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Date,
		arg.Note,
		arg.UserID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Date,
		&i.Note,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execresult
DELETE FROM transaction where id = $1 AND user_id=$2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
}

const getTransaction = `-- name: GetTransaction :many
SELECT transaction.id,
    transaction."name",
    transaction.amount,
    category."name" AS category,
    transaction."date",
    transaction.note,
    account."name" AS user,
    transaction.created_at,
    transaction.updated_at
FROM transaction
INNER JOIN account ON transaction.user_id = account.id
INNER JOIN category ON transaction.category  = category.id
WHERE transaction.user_id=$1
ORDER BY transaction.date DESC
`

type GetTransactionRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, userID uuid.UUID) ([]GetTransactionRow, error) {
	rows, err := q.db.Query(ctx, getTransaction, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionRow
	for rows.Next() {
		var i GetTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Category,
			&i.Date,
			&i.Note,
			&i.User,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
WITH updated AS (
    UPDATE transaction
    SET name = $2,
        amount = $3,
        category =  $4,
        date = $5,
        note = $6
    WHERE transaction.id = $1 AND transaction.user_id=$7
    RETURNING id, name, amount, category, date, note, user_id, created_at, updated_at
)
SELECT updated.id,
    updated."name",
    updated.amount,
    category."name" AS category,
    updated."date",
    updated.note,
    account."name" AS user,
    updated.created_at,
    updated.updated_at
FROM updated
INNER JOIN account ON updated.user_id = account.id
INNER JOIN category ON updated."category" = category.id
`

type UpdateTransactionParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Amount   pgtype.Numeric `json:"amount"`
	Category uuid.UUID      `json:"category"`
	Date     pgtype.Date    `json:"date"`
	Note     *string        `json:"note"`
	UserID   uuid.UUID      `json:"user_id"`
}

type UpdateTransactionRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	Date      pgtype.Date        `json:"date"`
	Note      *string            `json:"note"`
	User      string             `json:"user"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Date,
		arg.Note,
		arg.UserID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Date,
		&i.Note,
		&i.User,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
